### ISSUE TITLE
def foo -> Exception during compilation

### ISSUE THREAD

**Issue by fbertra** [jokade/scalajs-angulate#46]
A method definition without parentheses in a controller class generates a NoSuchElementException during compilation.

Reported against:
-  scalajs version: 0.6.2
-  scalaja-angulate version: 0.1

Example:

```
class CounterCtrl extends Controller {
  var count = 0

  def inc() = count += 1

  def dec() = count -= 1

  // foo () is ok
  def foo : Unit = println ("foo")
}
```

```
[error] /home/francois/proyectos/pruebas/scalajs-angular/src/main/scala/app/CounterApp.scala:12: exception during macro expansion: 
[error] java.util.NoSuchElementException: head of empty list
[error]         at scala.collection.immutable.Nil$.head(List.scala:420)
[error]         at scala.collection.immutable.Nil$.head(List.scala:417)
[error]         at biz.enef.angular.impl.MacroBase.makeArgsList(MacroBase.scala:36)
[error]         at biz.enef.angular.impl.ControllerMacroUtils$$anonfun$copyMembers$2.apply(ControllerMacros.scala:183)
[error]         at biz.enef.angular.impl.ControllerMacroUtils$$anonfun$copyMembers$2.apply(ControllerMacros.scala:181)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[error]         at scala.collection.immutable.List.foreach(List.scala:381)
[error]         at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[error]         at scala.collection.immutable.List.map(List.scala:285)
[error]         at biz.enef.angular.impl.ControllerMacroUtils$class.copyMembers(ControllerMacros.scala:181)
[error]         at biz.enef.angular.impl.ControllerMacros.copyMembers(ControllerMacros.scala:14)
[error]         at biz.enef.angular.impl.ControllerMacros.createController(ControllerMacros.scala:87)
[error]         at biz.enef.angular.impl.ControllerMacros.controllerOf(ControllerMacros.scala:29)
[error]     module.controllerOf[CounterCtrl]
```

**Comment by rparree** [comment]
I just tried your class quickly in my project and it compiles without a problem. Is this the code in your `CounterApp.scala` on line 12?

(same versions of dependencies as you)

It might be in some code using this?

**Comment by fbertra** [comment]
The complete CounterApp.scala example.

```
package app

import scala.scalajs.js.JSApp

import biz.enef.angular._

object CounterApp extends JSApp {
  def main(): Unit = {

    val module = Angular.module("counter", Nil)

    module.controllerOf[CounterCtrl] // line 12
  }
}

class CounterCtrl extends Controller {
  var count = 0

  def inc() = count += 1

  def dec() = count -= 1

  // foo () is ok
  def foo : Unit = println ("foo")
}
```

If I replace

```
    def foo: Unit = println ("foo")
```

with

```
    def foo () : Unit = println ("foo")
```

it compiles correctly.

**Comment by jokade** [comment]
This is a known bug (see #38) in v0.1 which has since been closed in 0.2-SNAPSHOT; can you upgrade to the latest snapshot version of angulate?

**Comment by fbertra** [comment]
Sorry for the duplicate report.

I can live with parentheses in method definition and wait for the definitive 2.0 version.

Thanks

**Comment by jokade** [comment]
no problem :)
I will probably release v0.2 this weekend

**Comment by rparree** [comment]
Just for sake of completion within this thread: I get indeed the same error once i add 

``` scala
module.controllerOf[CounterCtrl]
```
